# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(blank=True, default='sally', max_length=100, null=True)),
                ('contributor_email', models.EmailField(blank=True, default='sally@rit.edu', max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=100)),
                ('submitter_email', models.EmailField(default='sally@rit.edu', max_length=70)),
                ('doc_version', models.IntegerField()),
                ('doc_format', models.CharField(choices=[('PDF', 'PDF'), ('Word Document', 'Word Document')], max_length=6)),
                ('status', models.CharField(default='Submitted', max_length=500)),
                ('document', models.FileField(upload_to='sam_2017/docs/')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Paper_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=6)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.DocumentSubmission')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperSummary', models.CharField(blank=True, default='paper', max_length=500, null=True)),
                ('rating', models.CharField(blank=True, default='1', max_length=500, null=True)),
                ('reviewReasons', models.CharField(blank=True, default='average', max_length=500, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.DocumentSubmission')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(default='RIT', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentcontributor',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.DocumentSubmission'),
        ),
    ]
