# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20161106_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('PAPER_SUBMISSION', 'Paper Submission'), ('ACCOUNT_UPDATE', 'Account Update'), ('PCM_ACCOUNT_DELETION', 'PCM Account Deletion'), ('PCM_ASSIGNED_PAPER', 'PCM Assigned Paper')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request_paper_review',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=10),
        ),
    ]
