# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_deadline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('PAPER_SUBMISSION', 'Paper Submission'), ('ACCOUNT_UPDATE', 'Account Update'), ('PCM_ACCOUNT_DELETION', 'PCM Account Deletion'), ('PCM_ASSIGNED_PAPER', 'PCM Assigned Paper'), ('PAPER_SUBMISSION_REMINDER', 'Paper Submission Reminder')], max_length=50),
        ),
    ]
