# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20161117_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('PAPER_SUBMISSION_AUTHOR_NOTIF', 'Paper Submission Notification for Author'), ('PAPER_SUBMISSION_PCC_NOTIF', 'Paper Submission Notification for PCC'), ('REVIEW_REQUEST_PCM_NOTIF', 'Review Request Notification for PCM'), ('REVIEWS_COMPLETE_PCC_NOTIF', 'Reviews Complete Notification for PCC'), ('PAPER_SUBMISSION_REMINDER', 'Paper Submission Reminder for Authors'), ('PAPER_SUBMISSION_TODAY_REMINDER', 'Paper Submission Today Reminder for Authors'), ('REVIEW_REQUEST_REMINDER', 'Review Request Reminder for PCMs'), ('REVIEW_REQUEST_TODAY_REMINDER', 'Review Request Today Reminder for PCMs'), ('REVIEW_SUBMISSION_REMINDER', 'Review Submission Reminder for PCMs'), ('REVIEW_SUBMISSION_TODAY_REMINDER', 'Review Submission Today Reminder for PCMs')], max_length=50)),
                ('message', models.CharField(blank=True, default='Template message', max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('PAPER_SUBMISSION', 'Paper Submission'), ('ACCOUNT_UPDATE', 'Account Update'), ('PCM_ACCOUNT_DELETION', 'PCM Account Deletion'), ('PCM_ASSIGNED_PAPER', 'PCM Assigned Paper'), ('REVIEWS_COMPLETE', 'Reviews Complete'), ('PAPER_SUBMISSION_REMINDER', 'Paper Submission Reminder'), ('PCM_SUBMIT_REVIEW', 'PCM Submit Review'), ('PCM_SUBMIT_REVIEW_LIST', 'PCM Submit Review List')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request_paper_review',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10),
        ),
    ]
