# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_auto_20161204_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='type',
            field=models.CharField(choices=[('Paper Submit', 'Paper submission by Author'), ('Review List', 'Review list of choices by PCM'), ('Assign Paper', 'Assign paper to PCM'), ('Submit Review', 'Submit review of papers by PCM'), ('Final Review', 'Submit final review by PCC')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('PAPER_SUBMISSION_AUTHOR_NOTIF', 'Paper Submission Notification for Author'), ('PAPER_SUBMISSION_PCC_NOTIF', 'Paper Submission Notification for PCC'), ('REVIEW_REQUEST_APPROVED_PCM_NOTIF', 'Review Request Approved Notification for PCM'), ('REVIEW_REQUEST_REJECTED_PCM_NOTIF', 'Review Request Rejected Notification for PCM'), ('REVIEWS_COMPLETE_PCC_NOTIF', 'Reviews Complete Notification for PCC'), ('USER_ACCOUNT_UPDATE_NOTIF', 'User Account Update Notification'), ('FINAL_RATING_AUTHOR_NOTIF', 'Final Rating Notification for Author')], max_length=50, unique=True),
        ),
    ]
