# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-26 20:20
from __future__ import unicode_literals
from django.db import models, migrations
from django.contrib.auth.models import User, Group
from firstApp.models import ShareZone
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType




def add_group_permissions(firstApp, schemaeditor):
   #admin
   sharezone_admin, created = Group.objects.get_or_create(name='admin_user')
   if created:
       content_type = ContentType.objects.get_for_model(ShareZone)
       permission = Permission.objects.create(
           codename='can_change',
           name='Can Change ShareZone',
           content_type=content_type,
       )


       content_type1 = ContentType.objects.get_for_model(User)
       permission1 = Permission.objects.create(
           codename = "change_users",
           name = "Can Change Users",
           content_type = content_type1,
       )
       sharezone_admin.permissions.add(permission, permission1)


       system_admin, created1 = Group.objects.get_or_create(name='system_admin')
       if created1:
           content_type = ContentType.objects.get_for_model(ShareZone)
           permission1 = Permission.objects.create(
               codename='can_change_sys',
               name='Can Change ShareZone-a',
               content_type=content_type,
           )


           content_type1 = ContentType.objects.get_for_model(User)
           permission1 = Permission.objects.create(
               codename="change_users_sys",
               name="Can Change Users-b",
               content_type=content_type1,
           )
           system_admin.permissions.add(permission, permission1)


       basic_user, created2 = Group.objects.get_or_create(name='basic_user')


class Migration(migrations.Migration):


   dependencies = [
       ('firstApp', '0001_initial'),
   ]


   operations = [
       migrations.RunPython(add_group_permissions),
   ]